heat_template_version: 2015-04-30

description: Template to create a CaaSP cluster on OpenStack

parameter_groups:
  - label: general
    description: General Parameters
    parameters:
      - image
      - root_password

  - label: sizing
    description: Sizing Parameters
    parameters:
      - admin_flavor
      - master_flavor
      - worker_flavor
      - worker_count

  - label: network
    description: Network Parameters
    parameters:
      - external_net
      - internal_net_cidr
      - dns_nameserver

  - label: cpi
    description: CPI Parameters
    parameters:
      - cpi_auth_url
      - cpi_domain_name
      - cpi_tenant_name
      - cpi_region
      - cpi_username
      - cpi_password
      - cpi_monitor_max_retries
      - cpi_bs_version
      - cpi_ignore_volume_az

parameters:
  image:
    type: string
    description: Name of image to use for servers
    constraints:
      - custom_constraint: glance.image
  external_net:
    type: string
    description: >
      Name or ID of public network for which floating IP addresses will be allocated
    default: floating
  internal_net_cidr:
    type: string
    description: Private network range which servers get deployed. Make sure this doesn't conflict with the any IP addresses CaaSP uses (e.g. the dns_cluster_ip).
    default: 172.28.0.0/24
  dns_nameserver:
    type: string
    description: Address of a dns nameserver reachable.
    default: 172.28.0.2
  admin_flavor:
    type: string
    description: Admin Flavor
    default: m1.large
    constraints:
      - custom_constraint: nova.flavor
  master_flavor:
    type: string
    description: Master Flavor
    default: m1.large
    constraints:
      - custom_constraint: nova.flavor
  worker_flavor:
    type: string
    description: Worker Flavor
    default: m1.large
    constraints:
      - custom_constraint: nova.flavor
  worker_count:
    type: number
    description: Number of Worker nodes to boot
    default: 5
  root_password:
    type: string
    description: Root Password for the VMs
    default: linux

  cpi_auth_url:
    type: string
    description: Cloud Provider Interface - Keystone API URL
    default: https://api.keystone.example.net:5000/v3
  cpi_domain_name:
    type: string
    description: Cloud Provider Interface - Keystone domain name
    default: Default
  cpi_tenant_name:
    type: string
    description: Cloud Provider Interface - Keystone project name
    default: admin
  cpi_region:
    type: string
    description: Cloud Provider Interface - Keystone region
    default: RegionOne
  cpi_username:
    type: string
    description: Cloud Provider Interface - Keystone username
    default: admin
  cpi_password:
    type: string
    description: Cloud Provider Interface - Keystone user password
  cpi_monitor_max_retries:
    type: number
    description: Cloud Provider Interface - Neutron Load balancer monitoring max retries
    default: 3
  cpi_bs_version:
    type: string
    description: Cloud Provider Interface - Cinder block storage API version
    default: auto
    constraints:
      - allowed_values:
          - v1
          - v2
          - v3
          - auto
  cpi_ignore_volume_az:
    type: string
    description: Cloud Provider Interface - Ignore Nova and Cinder availability zone
    default: "true"

resources:
  keypair:
    type: OS::Nova::KeyPair
    properties:
      name:
        str_replace:
          template: {list_join: ['-', [{get_param: 'OS::stack_name'}, 'caasp-keypair']]}
          params:
            ".": "-"

  internal_network:
    type: OS::Neutron::Net
    properties:
      name:
        str_replace:
          template: {list_join: ['-', [{get_param: 'OS::stack_name'}, 'caasp-int-net']]}
          params:
            ".": "-"

  internal_subnet:
    type: OS::Neutron::Subnet
    properties:
      cidr: {get_param: internal_net_cidr}
      network: {get_resource: internal_network}
      dns_nameservers:
        - {get_param: dns_nameserver}

  external_router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info:
        network: {get_param: external_net}

  external_router_int:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: {get_resource: external_router}
      subnet: {get_resource: internal_subnet}

  secgroup_base:
    type: OS::Neutron::SecurityGroup
    properties:
      rules:
        - protocol: icmp
        - protocol: tcp
          port_range_min: 22
          port_range_max: 22
        - protocol: tcp
          port_range_min: 2379
          port_range_max: 2379
        - protocol: udp
          port_range_min: 8472
          port_range_max: 8472

  secgroup_admin:
    type: OS::Neutron::SecurityGroup
    properties:
      rules:
        - protocol: tcp
          port_range_min: 80
          port_range_max: 80
        - protocol: tcp
          port_range_min: 443
          port_range_max: 443
        - protocol: tcp
          port_range_min: 4505
          port_range_max: 4506
        - protocol: tcp
          port_range_min: 389
          port_range_max: 389

  secgroup_master:
    type: OS::Neutron::SecurityGroup
    properties:
      rules:
        - protocol: tcp
          port_range_min: 2380
          port_range_max: 2380
        - protocol: tcp
          port_range_min: 6443
          port_range_max: 6444
        - protocol: udp
          port_range_min: 8285
          port_range_max: 8285
        - protocol: tcp
          port_range_min: 30000
          port_range_max: 32768
        - protocol: udp
          port_range_min: 30000
          port_range_max: 32768

  secgroup_worker:
    type: OS::Neutron::SecurityGroup
    properties:
      rules:
        - protocol: tcp
          port_range_min: 80
          port_range_max: 80
        - protocol: tcp
          port_range_min: 443
          port_range_max: 443
        - protocol: tcp
          port_range_min: 8080
          port_range_max: 8080
        - protocol: tcp
          port_range_min: 8081
          port_range_max: 8081
        - protocol: tcp
          port_range_min: 2380
          port_range_max: 2380
        - protocol: tcp
          port_range_min: 10250
          port_range_max: 10250
        - protocol: udp
          port_range_min: 8285
          port_range_max: 8285
        - protocol: tcp
          port_range_min: 30000
          port_range_max: 32768
        - protocol: udp
          port_range_min: 30000
          port_range_max: 32768

  admin:
    type: OS::Nova::Server
    depends_on:
      - external_router_int
    properties:
      name: { list_join: ['-', [{get_param: 'OS::stack_name'}, 'admin']] }
      image: { get_param: image }
      key_name: { get_resource: keypair }
      flavor: { get_param: admin_flavor }
      networks:
        - port: { get_resource: admin_port }
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #cloud-config

            disable_root: False
            ssh_deletekeys: False
            ssh_pwauth: True

            chpasswd:
              list: |
                root:$root_password
              expire: False

            suse_caasp:
              role: admin

            ntp:
              enabled: true
              #servers:
              #  - ntp1.example.com
              #  - ntp2.example.com
              #  - ntp3.example.com
            runcmd:
              - /usr/bin/systemctl enable ntpd
              - /usr/bin/systemctl start ntpd
              - mkdir /etc/caasp/cpi
              - chmod -R 0755 /etc/caasp/cpi

            write_files:
              - path: /etc/caasp/cpi/openstack.conf
                permissions: '0644'
                content: |
                  auth-url=$cpi_auth_url
                  domain-name=$cpi_domain_name
                  tenant-name=$cpi_tenant_name
                  region=$cpi_region
                  username=$cpi_username
                  password=$cpi_password
                  subnet-id=$cpi_subnet_id
                  floating-network-id=$cpi_floating_network_id
                  monitor-max-retries=$cpi_monitor_max_retries
                  bs-version=$cpi_bs_version
                  ignore-volume-az=$cpi_ignore_volume_az
          params:
            $root_password: { get_param: root_password }
            $cpi_auth_url: { get_param: cpi_auth_url }
            $cpi_domain_name: { get_param: cpi_domain_name }
            $cpi_tenant_name: { get_param: cpi_tenant_name }
            $cpi_region: { get_param: cpi_region }
            $cpi_username: { get_param: cpi_username }
            $cpi_password: { get_param: cpi_password }
            $cpi_monitor_max_retries: { get_param: cpi_monitor_max_retries }
            $cpi_bs_version: { get_param: cpi_bs_version }
            $cpi_ignore_volume_az: { get_param: cpi_ignore_volume_az }
            $cpi_floating_network_id: { get_param: external_net }
            $cpi_subnet_id: { get_resource: internal_subnet }

  admin_port:
    type: OS::Neutron::Port
    depends_on:
      - external_router_int
    properties:
      network: { get_resource: internal_network }
      security_groups:
        - { get_resource: secgroup_base }
        - { get_resource: secgroup_admin }

  admin_floating_ip:
    type: OS::Neutron::FloatingIP
    depends_on:
      - external_router_int
    properties:
      floating_network: { get_param: external_net }

  admin_floating_ip_association:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_resource: admin_floating_ip }
      port_id: { get_resource: admin_port }

  master:
    type: OS::Nova::Server
    depends_on:
      - external_router_int
    properties:
      name: { list_join: ['-', [{get_param: 'OS::stack_name'}, 'master']] }
      image: { get_param: image }
      key_name: { get_resource: keypair }
      flavor: { get_param: master_flavor }
      networks:
        - port: { get_resource: master_port }
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #cloud-config

            disable_root: False
            ssh_deletekeys: False
            ssh_pwauth: True

            chpasswd:
              list: |
                root:$root_password
              expire: False

            suse_caasp:
              role: cluster
              admin_node: $admin_node

            ntp:
              enabled: true
              #servers:
              #  - ntp1.example.com
              #  - ntp2.example.com
              #  - ntp3.example.com
            runcmd:
              - /usr/bin/systemctl enable ntpd
              - /usr/bin/systemctl start ntpd
          params:
            $admin_node: { get_attr: [admin, first_address] }
            $root_password: { get_param: root_password }

  master_port:
    type: OS::Neutron::Port
    depends_on:
      - external_router_int
    properties:
      network: { get_resource: internal_network }
      security_groups:
        - { get_resource: secgroup_base }
        - { get_resource: secgroup_master }

  master_floating_ip:
    type: OS::Neutron::FloatingIP
    depends_on:
      - external_router_int
    properties:
      floating_network: { get_param: external_net }

  master_floating_ip_association:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_resource: master_floating_ip }
      port_id: { get_resource: master_port }

  worker:
    type: OS::Heat::ResourceGroup
    depends_on:
      - external_router_int
    properties:
      count: { get_param: worker_count }
      resource_def:
        type: OS::Nova::Server
        properties:
          name: { list_join: ['-', [{get_param: 'OS::stack_name'}, 'worker', '%index%']] }
          image: { get_param: image }
          key_name: { get_resource: keypair }
          flavor: { get_param: worker_flavor }
          networks:
            - network: { get_resource: internal_network }
          security_groups:
            - { get_resource: secgroup_base }
            - { get_resource: secgroup_worker }
          user_data_format: RAW
          user_data:
            str_replace:
              template: |
                #cloud-config

                disable_root: False
                ssh_deletekeys: False
                ssh_pwauth: True

                chpasswd:
                  list: |
                    root:$root_password
                  expire: False

                suse_caasp:
                  role: cluster
                  admin_node: $admin_node

                ntp:
                  enabled: true
                  #servers:
                  #  - ntp1.example.com
                  #  - ntp2.example.com
                  #  - ntp3.example.com
                runcmd:
                  - /usr/bin/systemctl enable ntpd
                  - /usr/bin/systemctl start ntpd
              params:
                $admin_node: { get_attr: [admin, first_address] }
                $root_password: { get_param: root_password }

                runcmd:
                  - transactional-update up
                  - reboot
